import type { AcceptanceCheck } from "@donelayer/shared";
import type { AgentRecord, WorkerRecord } from "./types";

export const demoAcceptanceChecks: AcceptanceCheck[] = [
  {
    id: "check-command",
    type: "COMMAND_EXIT",
    title: "Approved test command exits successfully",
    required: true,
    commandId: "NPM_TEST",
    allowedExitCodes: [0]
  },
  {
    id: "check-tests",
    type: "TEST",
    title: "Authentication tests pass",
    required: true,
    minimumTotal: 12,
    minimumPassed: 12,
    maximumFailed: 0
  },
  {
    id: "check-build",
    type: "BUILD",
    title: "Production build succeeds",
    required: true,
    commandId: "NPM_BUILD"
  },
  {
    id: "check-diff",
    type: "DIFF",
    title: "Code change is present",
    required: true,
    minimumChangedFiles: 1,
    requireNonEmptyPatch: true
  },
  {
    id: "check-file",
    type: "FILE_EXISTS",
    title: "Authentication test file exists",
    required: true,
    path: "src/auth/session.test.ts"
  },
  {
    id: "check-screenshot",
    type: "SCREENSHOT",
    title: "Test report screenshot uploaded",
    required: false,
    fileName: "test-report.png",
    minimumCount: 1
  },
  {
    id: "check-human",
    type: "HUMAN_APPROVAL",
    title: "Customer approves the evidence pack",
    required: true,
    approverKind: "CUSTOMER",
    allowAdminOverride: true
  }
];

export function createSeedAgents(timestamp: string): AgentRecord[] {
  return [
    {
      id: "agent-swift-rescue",
      slug: "swift-build-rescue",
      name: "Swift Build Rescue Agent",
      version: "1.4.2",
      providerId: "provider-alpha",
      providerName: "Provider Alpha",
      description: "Repairs Xcode build failures, Swift package conflicts and signing configuration in tightly scoped repositories.",
      skills: ["Swift", "Xcode", "SwiftUI", "SPM"],
      taskTypes: ["DIAGNOSE_REPOSITORY", "BUILD_RESCUE", "TEST_AND_FIX"],
      languages: ["Swift", "Objective-C"],
      operatingSystems: ["MACOS"],
      tools: ["Git", "Xcode", "xcodebuild", "SwiftLint"],
      requiredMcpServers: [],
      pricingModel: "FROM",
      basePriceCents: 18000,
      averageCompletionMinutes: 82,
      completedTasks: 148,
      verifiedSuccessRate: 0.91,
      rating: 4.8,
      workerStatus: "ONLINE",
      lastActiveAt: timestamp,
      verificationStatus: "VERIFIED",
      endpointType: "LOCAL_WORKER",
      endpointUrl: null,
      authenticationType: "NONE",
      inputModes: ["application/json"],
      outputModes: ["application/json", "text/x-diff"],
      acceptingTasks: true,
      recentFailures: 1,
      currentWorkload: 0,
      maxConcurrentJobs: 2,
      createdAt: timestamp,
      updatedAt: timestamp
    },
    {
      id: "agent-react-fix",
      slug: "react-bug-fix",
      name: "React Bug Fix Agent",
      version: "2.1.0",
      providerId: "provider-alpha",
      providerName: "Provider Alpha",
      description: "Finds and fixes scoped React and TypeScript defects with deterministic tests and readable evidence packs.",
      skills: ["React", "TypeScript", "Vitest", "Playwright", "Authentication"],
      taskTypes: ["TEST_AND_FIX", "FEATURE_COMPLETION", "BUILD_RESCUE"],
      languages: ["TypeScript", "JavaScript"],
      operatingSystems: ["WINDOWS", "LINUX"],
      tools: ["Git", "Node.js", "npm", "Playwright"],
      requiredMcpServers: [],
      pricingModel: "FIXED",
      basePriceCents: 22000,
      averageCompletionMinutes: 47,
      completedTasks: 231,
      verifiedSuccessRate: 0.94,
      rating: 4.9,
      workerStatus: "ONLINE",
      lastActiveAt: timestamp,
      verificationStatus: "VERIFIED",
      endpointType: "LOCAL_WORKER",
      endpointUrl: null,
      authenticationType: "NONE",
      inputModes: ["application/json"],
      outputModes: ["application/json", "text/x-diff"],
      acceptingTasks: true,
      recentFailures: 1,
      currentWorkload: 0,
      maxConcurrentJobs: 2,
      createdAt: timestamp,
      updatedAt: timestamp
    },
    {
      id: "agent-repo-qa",
      slug: "repository-qa",
      name: "Repository QA Agent",
      version: "1.8.5",
      providerId: "provider-beta",
      providerName: "Provider Beta",
      description: "Runs repository diagnostics, pull request verification and repeatable quality checks across common web stacks.",
      skills: ["Repository QA", "CI", "Testing", "GitHub Actions"],
      taskTypes: ["DIAGNOSE_REPOSITORY", "PULL_REQUEST_VERIFICATION", "TEST_AND_FIX"],
      languages: ["TypeScript", "Python", "Go"],
      operatingSystems: ["LINUX", "WINDOWS"],
      tools: ["Git", "Node.js", "Docker", "GitHub CLI"],
      requiredMcpServers: ["github"],
      pricingModel: "FROM",
      basePriceCents: 14000,
      averageCompletionMinutes: 64,
      completedTasks: 96,
      verifiedSuccessRate: 0.87,
      rating: 4.6,
      workerStatus: "OFFLINE",
      lastActiveAt: new Date(Date.parse(timestamp) - 3_600_000).toISOString(),
      verificationStatus: "VERIFIED",
      endpointType: "WEBHOOK",
      endpointUrl: "https://agents.example.invalid/repository-qa",
      authenticationType: "HMAC",
      inputModes: ["application/json"],
      outputModes: ["application/json"],
      acceptingTasks: true,
      recentFailures: 3,
      currentWorkload: 0,
      maxConcurrentJobs: 1,
      createdAt: timestamp,
      updatedAt: timestamp
    },
    {
      id: "agent-launch-ready",
      slug: "app-launch-readiness",
      name: "App Launch Readiness Agent",
      version: "1.2.3",
      providerId: "provider-beta",
      providerName: "Provider Beta",
      description: "Produces concise launch-readiness reports covering build, tests, lint, dependency health and basic security checks.",
      skills: ["Release Engineering", "Security", "CI", "Web Performance"],
      taskTypes: ["LAUNCH_READINESS", "DIAGNOSE_REPOSITORY", "PULL_REQUEST_VERIFICATION"],
      languages: ["TypeScript", "Python"],
      operatingSystems: ["LINUX"],
      tools: ["Git", "Node.js", "Docker", "Trivy"],
      requiredMcpServers: [],
      pricingModel: "FIXED",
      basePriceCents: 26000,
      averageCompletionMinutes: 108,
      completedTasks: 74,
      verifiedSuccessRate: 0.9,
      rating: 4.7,
      workerStatus: "OFFLINE",
      lastActiveAt: new Date(Date.parse(timestamp) - 86_400_000).toISOString(),
      verificationStatus: "PENDING",
      endpointType: "A2A",
      endpointUrl: "https://agents.example.invalid/.well-known/agent-card.json",
      authenticationType: "A2A_METADATA",
      inputModes: ["text/plain"],
      outputModes: ["application/json"],
      acceptingTasks: false,
      recentFailures: 2,
      currentWorkload: 0,
      maxConcurrentJobs: 1,
      createdAt: timestamp,
      updatedAt: timestamp
    }
  ];
}

export function createSeedWorkers(timestamp: string): WorkerRecord[] {
  return [
    {
      id: "20000000-0000-4000-8000-000000000001",
      providerId: "provider-alpha",
      name: "macOS Worker 01",
      status: "ONLINE",
      os: "MACOS",
      installedTools: ["Git", "Xcode", "xcodebuild", "SwiftLint"],
      mcpTools: [],
      executors: ["DEMO", "CODEX"],
      maxConcurrentJobs: 2,
      activeJobs: 0,
      lastHeartbeatAt: timestamp,
      tokenHash: null,
      tokenId: null,
      acceptingJobs: true,
      createdAt: timestamp,
      updatedAt: timestamp
    },
    {
      id: "20000000-0000-4000-8000-000000000002",
      providerId: "provider-alpha",
      name: "Windows Worker 01",
      status: "ONLINE",
      os: "WINDOWS",
      installedTools: ["Git", "Node.js", "npm", "Playwright"],
      mcpTools: [],
      executors: ["DEMO"],
      maxConcurrentJobs: 2,
      activeJobs: 0,
      lastHeartbeatAt: timestamp,
      tokenHash: null,
      tokenId: null,
      acceptingJobs: true,
      createdAt: timestamp,
      updatedAt: timestamp
    },
    {
      id: "20000000-0000-4000-8000-000000000003",
      providerId: "provider-beta",
      name: "Linux Worker Offline",
      status: "OFFLINE",
      os: "LINUX",
      installedTools: ["Git", "Node.js", "Docker", "GitHub CLI", "Trivy"],
      mcpTools: ["github:pull_requests.read", "github:checks.read"],
      executors: ["DEMO", "WEBHOOK"],
      maxConcurrentJobs: 1,
      activeJobs: 0,
      lastHeartbeatAt: new Date(Date.parse(timestamp) - 3_600_000).toISOString(),
      tokenHash: null,
      tokenId: null,
      acceptingJobs: false,
      createdAt: timestamp,
      updatedAt: timestamp
    }
  ];
}
